### ISSUE TITLE
Check failed: ExactNumBottomBlobs() == bottom.size() (2 vs. 3) SoftmaxWithLoss Layer 

### ISSUE THREAD

**Issue by ghost** [chungjin/caffe-R-FCN#1]
Hello:
 When I use your caffe to train faster rcnn's RPN, I meet this problem:

proposal_cls_score_reshape_proposal_cls_score_reshape_0_split_0
 I0917 13:23:32.705237 11568 net.cpp:444] loss <- labels_reshape_labels_reshape_0_split_0
 I0917 13:23:32.705237 11568 net.cpp:444] loss <- labels_weights_reshape
 I0917 13:23:32.705237 11568 net.cpp:418] loss -> loss_cls

**F0917 13:23:32.705237 11568 layer.hpp:385] Check failed: ExactNumBottomBlobs() == bottom.size() (2 vs. 3) SoftmaxWithLoss Layer takes 2 bottom blob(s) as input.
 F0917 13:23:32.705237 11568 layer.hpp:385] Check failed: ExactNumBottomBlobs() == bottom.size() (2 vs. 3) SoftmaxWithLoss Layer takes 2 bottom blob(s) as input.**

Help me!
 Thanks!

**Comment by chungjin** [comment]
你好，你的batch size是设置为1张image吗？
在experiment/cfgs/rfcn_end2end_ohem.yml中定义。

**Comment by ghost** [comment]
您好，我是用您的caffe编译windows下matlab版本的faster rcnn，rpn的softmaxwithloss有三个输入，其中一个是权重，所以就有这个问题。
P.S: linux 下您的caffe没有问题。谢谢
