### ISSUE TITLE
GCC version compatibility

### ISSUE THREAD

**Issue by gusdoe** [chungjin/caffe-R-FCN#2]
Hi Zhang-Jin & all contributors,

While I was trying to compile caffe-R-FCN with gcc 5.4, I have confronted some compiling errors. I am wondering what gcc veriosn you have used to compile it. I assumed the update is still going on. Please let me know if you re going to stage the complete version. 

Cheers

Gus Doh

**Comment by chungjin** [comment]
my g++ version is 4.4.6, because I don't have the root permission, so I have changed the code from https://github.com/Microsoft/caffe.git, and let it can be compiled by the lower version compiler in my server.

**Comment by gusdoe** [comment]
Thank you Jin for the answer!

Are you sure you have made your github repository up to date? The code you
posted looks like uncompleted. Some basic grammars and undefined functions
are used. I can chase those errors but I thought its better to confirm from
you defore I do it.

Kind regards,

Gus Doh

**Comment by chungjin** [comment]
I have test the code and all goes well, but some function like smoothl1loss layer doesn't support the cpu mode, besides you can only use it in linux os. Because I did not use the code in windows os, maybe you can refer the https://github.com/Microsoft/caffe.git, if you want to use it in windows.

**Comment by shuh15** [comment]
Hi Zhang-Jin, the code you posted really looks like uncompleted, some ";" and  "}" are missing and some functions are not declared. eg, caffe_cpu_set() and caffe_cpu_atomic_add() in psroi_pooling_layer.cpp, the hpps and cpps don't match each other.

**Comment by chungjin** [comment]
yes, the cpu mode is just a trial, and the repo only supports the GPU function. But I had just committed a new version, now it supports the CPU, but cannot trained in CPU mode, because I only write the CPU function in forward.

**Comment by shuh15** [comment]
Thank u！I have seen that！

**Comment by chungjin** [comment]
U r welcome~ Please inform me if you encounter any problems when running the code.
